---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
```

```{r}
probes = readRDS("~/illumina_probes_hg38_GRanges.RDS")
refExtended = read.csv("/local/agosdsc/projects/AAkalin_cfdTissue/results/extendedReference.csv")


```

```{r}
sample_ids = c(
 'N1', # control
 'N2',
 'N3',
 'N4',
 'N5',
 'N6',
 'H26',
 'H28',
 'AC1', #stemi
 'AC2',
 'AC3',
 'AC4',
 'AC5',
 'AC6',
 'AC14',
 'AC15',
 'AC7',# nstemi
 'AC8',
 'AC9',
 'AC10',
 'AC11', 
 'AC12',
 'AC13',
 'AP1', #Acs/iAP
 'AP2',
 'AP3',
 'AP4',
 'AP5',  
 'AP6',
 'CS1', # CAD+posStressEcho+negIntervention
 'CS2',
 'CS3',
 'CS4', # CAD+posStressEcho+posIntervention
 'CS5',
 'CS6'
)
treatment1=c(
    rep(0,8),  # control
    rep(1,8), #stemi
    rep(2,7),  # nstemi
    rep(3,6), #Acs/iAP
    rep(4,3), #CAD+posStressEcho+negIntervention
    rep(5,3) #CAD+posStressEcho+posIntervention
     )


treatment_descr=c(
  rep("Control",8),  # control
  rep("ACS_Stemi",8), #stemi
  rep("ACS_Nstemi",7),  # nstemi
  rep("ACS_iAP",6), #Acs/iAP
  rep("CAD+posStressEcho+neg",3),
  rep("CAD+posStressEcho+pos",3)
)

methT.path = '/local/AAkalin_cardiac/Results/cardiac/06_methyl_calls_bwameth/tileMethylCounts/methylBase_CpG_dT_tiles_win500bp_step500bp_123batch_v1.txt.bgz'
meth.deT=methylKit:::readMethylBaseDB(methT.path,"tabix",
                                      sample_ids, "hg38" ,"CpG",
                                      "region",treatment =  treatment1,TRUE,skip=0)
```


```{r}
desc<-data.frame(treatment1,treatment_descr,sample_ids)
desc<-desc %>% rename("treatment"="treatment1")
desc<-unique(desc)
desc$treatment_descr <- gsub("iAP","UA",desc$treatment_descr)
```




```{r}
meth.deT@treatment=treatment1
mapping = deconvR::BSmeth2Probe(probe_id_locations = probes, WGBS_data = meth.deT)

```

```{r}
decon_nnls_extended = deconvR::deconvolute(reference=refExtended, bulk=mapping, model="nnls")

decon_nnls_extended_0 = decon_nnls_extended[1:8,]    
decon_nnls_extended_1 = decon_nnls_extended[9:16,]
decon_nnls_extended_2 = decon_nnls_extended[17:23,]
decon_nnls_extended_3 = decon_nnls_extended[24:29,]
decon_nnls_extended_4 = decon_nnls_extended[30:32,]
decon_nnls_extended_5 = decon_nnls_extended[33:35,]
decon_nnls_extended.m   = reshape2::melt(decon_nnls_extended)
decon_nnls_extended_0.m = reshape2::melt(decon_nnls_extended_0)
decon_nnls_extended_1.m = reshape2::melt(decon_nnls_extended_1)
decon_nnls_extended_2.m = reshape2::melt(decon_nnls_extended_2)
decon_nnls_extended_3.m = reshape2::melt(decon_nnls_extended_3)
decon_nnls_extended_4.m = reshape2::melt(decon_nnls_extended_4)
decon_nnls_extended_5.m = reshape2::melt(decon_nnls_extended_5)


```

```{r}
#decon_nnls_extended.m
```


```{r}
decon_nnls_extended_tgs.m = cbind(decon_nnls_extended.m,"treatment"= methylKit::getTreatment(meth.deT),"samples_id"= methylKit::getSampleID(meth.deT))

decon_nnls_extended_tgs.m <-decon_nnls_extended_tgs.m %>% filter(treatment != 4 & treatment != 5)

decon_nnls_extended_tgs.m$treatment_descr <-decon_nnls_extended_tgs.m$treatment

decon_nnls_extended_tgs.m$treatment_descr <-str_replace(decon_nnls_extended_tgs.m$treatment_descr,"0","Healthy")
decon_nnls_extended_tgs.m$treatment_descr <-str_replace(decon_nnls_extended_tgs.m$treatment_descr,"1","Stemi")
decon_nnls_extended_tgs.m$treatment_descr <-str_replace(decon_nnls_extended_tgs.m$treatment_descr,"2","Nstemi")
decon_nnls_extended_tgs.m$treatment_descr <-str_replace(decon_nnls_extended_tgs.m$treatment_descr,"3","UA")
decon_nnls_extended_tgs.m$treatment_descr <- factor(decon_nnls_extended_tgs.m$treatment_descr , levels=c("Stemi", "Nstemi", "UA","Healthy"))

```




```{r}
saveRDS(decon_nnls_extended_tgs.m,"../Results/cardiac/RDS/decon_cell_proportions.RDS")
```

```{r}
decon_nnls_extended_tgs.m_normalized<-decon_nnls_extended_tgs.m

```




```{r}
#does not work, got from descriptive_stats
# suppl_tbl_2<-readRDS("/home/rcastro/suppl_tbl_2.RDS")

```

```{r}
tbl_2<-suppl_tbl_2 %>% dplyr::select(Sample,cfDNA_ug_per_ml_plasma) %>% rename(
      samples_id = Sample )
```


```{r}
decon_nnls_extended_tgs.m_normalized<-left_join(decon_nnls_extended_tgs.m_normalized,tbl_2,by="samples_id")
```


```{r}
decon_nnls_extended_tgs.m_normalized
```



```{r,fig.height=16,fig.width=10}
bp_decon_nnls_extended <- ggplot2::ggplot(decon_nnls_extended_tgs.m, ggplot2::aes(x=reorder(variable,value), y=value, fill=factor(treatment_descr))) + ggplot2::geom_boxplot()

bp_decon_nnls_extended + ggplot2::theme(legend.text=element_text(size=14),axis.text.x = ggplot2::element_text(size=14),axis.text.y = ggplot2::element_text(size=14), plot.title = ggplot2::element_text(size=14)) + ggplot2::labs(fill="Treatment",x = "Cell Type", y = "Proportion of Sample") + coord_flip()


```



```{r}
decon_nnls_extended_tgs.m_short <-decon_nnls_extended_tgs.m %>% filter(variable != "Adipocytes" & 
                                         variable != "Lung_cells" & 
                                         variable != "Pancreatic_beta_cells" & 
                                         variable != "Pancreatic_acinar_cells"	 &
                                         variable != "Pancreatic_duct_cells" &
                                         variable != "Colon_epithelial_cells" &
                                         variable != "Head_and_neck_larynx" &
                                         variable != "Prostate" &
                                         variable != "Upper_GI" &
                                         variable != "Left_atrium" &
                                         variable != "right_atrium_auricular_region" &
                                         variable != "Breast" &
                                         variable != "Uterus_cervix"
                                         )
```


```{r}
decon_nnls_extended_tgs.m_normalized <-decon_nnls_extended_tgs.m_normalized %>% filter(variable != "Adipocytes" & 
                                         variable != "Lung_cells" & 
                                         variable != "Pancreatic_beta_cells" & 
                                         variable != "Pancreatic_acinar_cells"	 &
                                         variable != "Pancreatic_duct_cells" &
                                         variable != "Colon_epithelial_cells" &
                                         variable != "Head_and_neck_larynx" &
                                         variable != "Prostate" &
                                         variable != "Upper_GI" &
                                         variable != "Left_atrium" &
                                         variable != "right_atrium_auricular_region" &
                                         variable != "Breast" &
                                         variable != "Uterus_cervix"
                                         )
```


```{r}
decon_nnls_extended_tgs.m_short$value = decon_nnls_extended_tgs.m_short$value * 100

```




```{r}
decon_nnls_extended_tgs.m_normalized$value = decon_nnls_extended_tgs.m_normalized$value * decon_nnls_extended_tgs.m_normalized$cfDNA_ug_per_ml_plasma
decon_nnls_extended_tgs.m_normalized$method <- "ccfDNA (μg/ml of plasma)"
```




```{r}
decon_nnls_extended_tgs.m_short$method <- "% of cell/tissue"
```


```{r}
decon_nnls_extended_all_short<-rbind(decon_nnls_extended_tgs.m_short,decon_nnls_extended_tgs.m_normalized %>% dplyr::select(-cfDNA_ug_per_ml_plasma))
```

```{r}
decon_nnls_extended_all_short$treatment_descr <- factor(decon_nnls_extended_all_short$treatment_descr , levels=c("Stemi", "Nstemi", "UA","Healthy"))

```

```{r}
decon_nnls_extended_all_short_even_shorter <-decon_nnls_extended_all_short %>% filter(variable =="Vascular_endothelial_cells" | variable =="heart_left_ventricle" | variable =="Erythrocyte_progenitors" | variable =="coronary_artery" | variable =="Monocytes_EPIC"  | variable == "CD4T.cells_EPIC" | variable == "NK.cells_EPIC" | variable =="Kidney" | variable == "Neutrophils_EPIC" | variable =="Hepatocytes")

   
 
```


```{r}
decon_nnls_extended_all_short_even_shorter$variable <-str_replace(decon_nnls_extended_all_short_even_shorter$variable,"_EPIC","")
decon_nnls_extended_all_short_even_shorter$variable <-str_replace(decon_nnls_extended_all_short_even_shorter$variable,"_"," ")
decon_nnls_extended_all_short_even_shorter$variable <-str_replace(decon_nnls_extended_all_short_even_shorter$variable,".cells","")



```

```{r}
decon_nnls_extended_all_short_even_shorter$variable <-str_replace(decon_nnls_extended_all_short_even_shorter$variable,"_"," ")

```

```{r}
decon_nnls_extended_all_short_even_shorter
```


```{r}

bp_decon_nnls_extended <- ggplot2::ggplot(decon_nnls_extended_all_short_even_shorter %>% filter(method == "% of cell/tissue"), ggplot2::aes(x=variable, y=value, fill=factor(treatment_descr))) + ggplot2::geom_boxplot()

bp_decon_nnls_extended +   theme_Publication() + scale_fill_Publication() + ggplot2::theme(axis.text.x = element_blank(),strip.text = element_text(size=12),legend.text=element_text(size=14),axis.title.x = element_blank()) + ggplot2::labs(fill="Group",x = "treatment_descr", y = "% of cell/tissue") + ggplot2::facet_wrap(~variable, scale="free",ncol = 4) 

ggplot2::ggsave(filename = "/local/AAkalin_cardiac/Results/cardiac/Plots/Figure2.pdf", 
plot =  last_plot(), 
width = 12,
height = 12)


```

```{r,fig.height=18,fig.width=12}
#pdf(file = "/local/AAkalin_cardiac/Results/cardiac/Plots/Figure2.pdf",height = 18,width = 12)


bp_decon_nnls_extended <- ggplot2::ggplot(decon_nnls_extended_all_short_even_shorter, ggplot2::aes(x=variable, y=value, fill=factor(treatment_descr))) + ggplot2::geom_boxplot()

bp_decon_nnls_extended +   theme_Publication() + scale_fill_Publication() + ggplot2::theme(axis.text.x = element_blank(),strip.text = element_text(size=12),legend.text=element_text(size=14),axis.title.x = element_blank()) + ggplot2::labs(fill="Group",x = "treatment_descr", y = "") + ggplot2::facet_wrap(~variable + method, scale="free",ncol = 4) 

ggplot2::ggsave(filename = "/local/AAkalin_cardiac/Results/cardiac/Plots/Figure2.pdf", 
plot =  last_plot(), 
width = 12,
height = 18)

#dev.off()
```


```{r}
saveRDS(decon_nnls_extended_all_short,"decon_nnls_extended_all_short.RDS")
```


```{r,fig.height=16,fig.width=12}


bp_decon_nnls_extended <- ggplot2::ggplot(decon_nnls_extended_all_short, ggplot2::aes(x=reorder(variable,value), y=value, fill=factor(treatment_descr))) + ggplot2::geom_boxplot()

bp_decon_nnls_extended + ggplot2::theme(legend.text=element_text(size=14),axis.text.x = ggplot2::element_text(size=14), axis.text.y = ggplot2::element_text(size=14),plot.title = ggplot2::element_text(size=16)) + ggplot2::labs(fill="Treatment",x = "", y = "") + coord_flip() + facet_wrap(~method,scales = "free_x")



```




```{r,fig.height=16,fig.width=10}
bp_decon_nnls_extended <- ggplot2::ggplot(decon_nnls_extended_tgs.m_short, ggplot2::aes(x=reorder(variable,value), y=value, fill=factor(treatment_descr))) + ggplot2::geom_boxplot()

bp_decon_nnls_extended + ggplot2::theme(legend.text=element_text(size=14),axis.text.x = ggplot2::element_text(size=14), axis.text.y = ggplot2::element_text(size=14),plot.title = ggplot2::element_text(size=20)) + ggplot2::labs(fill="Treatment",x = "Cell Type", y = "Proportion of Sample") + coord_flip()


ggsave(
  "../Results/cardiac/Plots/Figure2.pdf",
  device = "pdf",
  plot = last_plot())
```


```{r}

```


```{r}
bp_decon_nnls_extended <- ggplot2::ggplot(decon_nnls_extended_tgs.m_short, ggplot2::aes(x=variable, y=value, fill=factor(treatment_descr))) + ggplot2::geom_boxplot()

```



```{r,fig.height=20,fig.width=16}
bp_decon_nnls_extended + ggplot2::theme(axis.text.x = element_blank(),strip.text = element_text(size=16),legend.text=element_text(size=14),axis.title.x = element_blank()) + ggplot2::labs(fill="Treatment",x = "Cell Type", y = "Proportion of Sample") + ggplot2::facet_wrap(~variable, scale="free") + ggplot2::scale_y_continuous(expand = c(0, 0), limits = c(0, NA))
```


```{r}
neut_health<-decon_nnls_extended_tgs.m_short %>% filter(variable == "Neutrophils_EPIC" & treatment ==0) %>% dplyr::select(value)


```

```{r}
mean(neut_health$value)
```


```{r}
health_composition<-decon_nnls_extended_tgs.m %>% filter(treatment ==0) %>% group_by(variable) %>% summarise_at("value",mean)
```


```{r}
 
```


