---
title: "RoadMap_enrichment"
output: html_notebook
---

# Load Libraries
```{r}
require(tidyverse)
library(reshape2)
library(GenomicRanges)
require(MetBrewer)
library(viridis)
require(RColorBrewer)
```

# Load input data
```{r}
road_map <- read.table("databases/prom_enh.csv", sep = "\t", header = TRUE)
main <- read.table("test/main.STEMI.csv", header = TRUE)
samples <- read.table("test/samples.STEMI.csv", header = TRUE)


cell_types <- (unfactor(unique(road_map$Sample_desc)))

Heart_vascular <- c("Fetal Heart", "Right Atrium", "Left Ventricle", "Right Ventricle", "Aorta", "HUVEC Umbilical Vein Endothelial Primary Cells")

Carcinoma <- cell_types[grep("Carcinoma", cell_types)]
Blood <- cell_types[grep("blood|T helper|Leukemia|Monocytes", cell_types)]
Skeletal_Muscle <- cell_types[grep("Skeletal Muscle|Fetal Muscle|Psoas|Muscle Satellite", cell_types)]
Stem <- cell_types[grep("Stem|stem|ES|H1|H9|hESC|iPS|HUE", cell_types)]
Nervous_system <- cell_types[grep("Brain|neurospheres", cell_types)]
Digestive <- cell_types[grep("Stomach|Gastric|Esophagus|Intestine|Duodenum|Rectal|Colonic|Colon", cell_types)]
Foreskin <- cell_types[grep("Foreskin", cell_types)]
Lung <- cell_types[grep("Lung|lung", cell_types)]
Lung <- Lung[!grepl("Carcinoma", Lung)]
Breast <- cell_types[grep("Breast|HMEC", cell_types)]
Pancreas <- cell_types[grep("Pancrea", cell_types)]
Lymphatic <- cell_types[grep("Thymus|Spleen", cell_types)]
cells_tissues_groups <- cbind(
  Heart_vascular, Carcinoma, Blood, Skeletal_Muscle, Stem, Nervous_system, Digestive,
  Foreskin, Lung, Breast, Pancreas, Lymphatic
)
cells_tissues_groups <- melt(cells_tissues_groups) %>%
  select(-Var1) %>%
  unique()
Others <- cell_types[!(cell_types %in% cells_tissues_groups$value)]
Others <- data.frame("Others", Others)
names(Others) <- c("Var2", "value")
cells_tissues_groups <- rbind(cells_tissues_groups, Others)
names(cells_tissues_groups) <- c("Cell_group", "celltype")
```

# Analysis
## Testing things here
```{r Testing_1}
percc <- t(main[1, ] %>% dplyr::select(-chr, -start, -end))
samples <- samples %>% column_to_rownames(var = "sampleId")
meeerge <- merge(samples, percc, by = 0)
```


```{r Testing_2}
p <- ggplot(meeerge, aes(x = Type, y = meeerge[, 3], fill = Type)) +
  geom_boxplot() +
  theme_bw()
p
```

## Annotate DMR roadmap
```{r Function_Annotate_DMR_roadmap}
annotate_DMR_roadmap <- function(DMRs, road_map) {
  # make a Genomic range with DMR tiles
  main <- DMRs
  nDMRs <- nrow(main)
  road_map <- road_map
  gr_DMR <- makeGRangesFromDataFrame(main %>% dplyr::select(chr, start, end))

  # find overlap with road_map enhancers/promoters on DMR tiles
  tmp_bed2 <- findOverlaps(gr_DMR, as(road_map, "GRanges"))
  tmp_bed2 <- data.frame(tmp_bed2)
  tmp_bed3 <- data.frame(gr_DMR[tmp_bed2$queryHits])
  tmp_bed4 <- data.frame(as(road_map, "GRanges")[tmp_bed2$subjectHits])
  tmp_bed4 <- tmp_bed4 %>% dplyr::select(SampleID, Sample_desc)
  final_enhancer_annotated <- merge(tmp_bed3, tmp_bed4, by = 0)
  final_enhancer_annotated$DMR <- paste0(final_enhancer_annotated$seqnames, "_", final_enhancer_annotated$start, "_", final_enhancer_annotated$end)
  final_enhancer_annotated <- final_enhancer_annotated %>% dplyr::select(DMR, Sample_desc)
  final_enhancer_annotated <- final_enhancer_annotated %>% unique()

  enh_matrix <- dcast(final_enhancer_annotated, DMR ~ Sample_desc, length)
  enh_matrix <- enh_matrix %>%
    remove_rownames() %>%
    column_to_rownames(var = "DMR")

  # count number of DMR tiles annotated for each celltype, calculate perc of those of the total tiles on DMR
  disease_enhancer_annotated <- data.frame(colSums(enh_matrix), (colSums(enh_matrix) / nDMRs * 100))
  names(disease_enhancer_annotated) <- c("DMR", "perc_DMR")
  out <- list(disease_enhancer_annotated, final_enhancer_annotated)
  names(out) <- c("disease_enhancer_annotated", "final_enhancer_annotated")
  return(out)
}
```

```{r Run_function_annotate_DMR_roadmap}
result <- annotate_DMR_roadmap(main, road_map)
```

```{r Collapse_result}
result$final_enhancer_annotated %>%
  separate(DMR, c("chr", "start", "end")) %>%
  group_by(chr, start, end) %>%
  mutate(Sample_desc = paste0(Sample_desc, collapse = "|")) %>%
  unique()
```

## Extract a background and run enrichment test for cell types on DMRs
```{r Function_background_and_enrichment_tests}
enrichment_cells <- function(DMRs, DM, w, h) {
  main <- read.table(DMRs, header = TRUE)
  # get just regions of DMR
  DMRs <- main %>% select(chr, start, end)
  # calculate 1000bp distant tiles
  DMRs$start_prev <- DMRs$start - 1000
  DMRs$end_prev <- DMRs$end - 1000

  DMRs$start_after <- DMRs$start + 1000
  DMRs$end_after <- DMRs$end + 1000

  # getting the regions after and before DMR (1000bp distant)
  prev <- DMRs %>%
    select(chr, start_prev, end_prev) %>%
    rename("start_prev" = "start", "end_prev" = "end")
  after <- DMRs %>%
    select(chr, start_after, end_after) %>%
    rename("start_after" = "start", "end_after" = "end")
  background_regions <- rbind(prev, after)

  DM_test <- read.table(DM, sep = "\t", header = TRUE)
  DM_test <- DM_test %>% rename("seqnames" = "chr")
  background_regions <- merge(background_regions, DM_test, by = c("chr", "start", "end"), all.x = TRUE)
  background_regions_notsig <- background_regions %>% filter(qvalue > 0.05 | is.na(qvalue))
  background <- background_regions_notsig %>% select(chr, start, end)
  # number of tiles in the background
  ntiles <- nrow(background)
  # make a Genomic range with background tiles
  gr_background <- makeGRangesFromDataFrame(background)

  # find overlap with road_map enhancers/promoters on background tiles
  tmp_bed2 <- findOverlaps(gr_background, as(road_map, "GRanges"))
  tmp_bed2 <- data.frame(tmp_bed2)
  tmp_bed3 <- data.frame(gr_background[tmp_bed2$queryHits])
  tmp_bed4 <- data.frame(as(road_map, "GRanges")[tmp_bed2$subjectHits])
  tmp_bed4 <- tmp_bed4 %>% dplyr::select(SampleID, Sample_desc)
  background_enhancer_annotated <- merge(tmp_bed3, tmp_bed4, by = 0)
  background_enhancer_annotated$DMR <- paste0(background_enhancer_annotated$seqnames, "_", background_enhancer_annotated$start, "_", background_enhancer_annotated$end)
  background_enhancer_annotated <- background_enhancer_annotated %>% dplyr::select(DMR, Sample_desc)
  background_enhancer_annotated <- background_enhancer_annotated %>% unique()

  background_enhancer_matrix <- dcast(background_enhancer_annotated, DMR ~ Sample_desc, length)
  background_enhancer_matrix <- background_enhancer_matrix %>%
    remove_rownames() %>%
    column_to_rownames(var = "DMR")

  # count number of background tiles annotated for each celltype, calculate perc of those of the total tiles on background
  background_enhancer_annotated <- data.frame(colSums(background_enhancer_matrix), (colSums(background_enhancer_matrix) / ntiles * 100))
  names(background_enhancer_annotated) <- c("Background", "perc_Background")

  # processing main file with DMRs
  # making a genomic range out of it, looking for overlaps with df3 that is
  # the roadmap dataframe with promoters and enhanceers regions for cell types
  # main=read.table("test/main.STEMI.csv",header=TRUE)
  # number of tiles in the DMR results
  nDMRs <- nrow(main)
  # make a Genomic range with DMR tiles
  gr_DMR <- makeGRangesFromDataFrame(main %>% dplyr::select(chr, start, end))
  # find overlap with road_map enhancers/promoters on DMR tiles
  tmp_bed2 <- findOverlaps(gr_DMR, as(road_map, "GRanges"))
  tmp_bed2 <- data.frame(tmp_bed2)
  tmp_bed3 <- data.frame(gr_DMR[tmp_bed2$queryHits])
  tmp_bed4 <- data.frame(as(road_map, "GRanges")[tmp_bed2$subjectHits])
  tmp_bed4 <- tmp_bed4 %>% dplyr::select(SampleID, Sample_desc)
  final_enhancer_annotated <- merge(tmp_bed3, tmp_bed4, by = 0)
  final_enhancer_annotated$DMR <- paste0(final_enhancer_annotated$seqnames, "_", final_enhancer_annotated$start, "_", final_enhancer_annotated$end)
  final_enhancer_annotated <- final_enhancer_annotated %>% dplyr::select(DMR, Sample_desc)
  final_enhancer_annotated <- final_enhancer_annotated %>% unique()

  enh_matrix <- dcast(final_enhancer_annotated, DMR ~ Sample_desc, length)
  enh_matrix <- enh_matrix %>%
    remove_rownames() %>%
    column_to_rownames(var = "DMR")

  # count number of DMR tiles annotated for each celltype, calculate perc of those of the total tiles on DMR
  disease_enhancer_annotated <- data.frame(colSums(enh_matrix), (colSums(enh_matrix) / nDMRs * 100))
  names(disease_enhancer_annotated) <- c("DMR", "perc_DMR")

  # merge background and disease counts and percs
  final_perc <- merge(background_enhancer_annotated, disease_enhancer_annotated, by = 0)
  final_perc <- final_perc %>%
    remove_rownames() %>%
    column_to_rownames(var = "Row.names")

  nDMRs <- nrow(main)
  ntiles <- nrow(background_regions_notsig)

  results <- data.frame(matrix(ncol = 5))
  x <- c("celltype", "pvalue", "odds", "min", "max")
  colnames(results) <- x
  for (row in 1:nrow(final_perc)) {
    not_cell_back <- ntiles - final_perc$Background[row]

    not_cell_DMR <- nDMRs - final_perc$DMR[row]

    tab_cont <- matrix(c(final_perc$Background[row], not_cell_back, final_perc$DMR[row], not_cell_DMR), nrow = 2, ncol = 2)

    fisher_result <- fisher.test(tab_cont)
    pvalue <- fisher_result$p.value
    min <- fisher_result$conf.int[1]
    max <- fisher_result$conf.int[2]
    odds <- fisher_result$estimate[[1]]
    celltype <- row.names(final_perc[row, ])
    a <- data.frame(celltype = celltype, pvalue = pvalue, odds = odds, min = min, max = max)
    results <- rbind(results, a)
  }
  results <- results[-1, ]

  sig_res <- results %>% dplyr::filter(pvalue <= 0.05 / 127)


  melt_perc <- melt(final_perc %>% rownames_to_column("celltype") %>% dplyr::select(celltype, perc_Background, perc_DMR))
  sig_res <- merge(sig_res, melt_perc, by = "celltype")
  sig_res$variable <- gsub("perc_", "", sig_res$variable)
  sig_res <- merge(sig_res, cells_tissues_groups, by = "celltype")


  sig_res$celltype <- as.factor(sig_res$celltype)
  sig_res <- sig_res %>%
    group_by(Cell_group) %>%
    mutate(median_group = median(pvalue))
  sig_res <- ungroup(sig_res)


  pper <- ggplot(sig_res, aes(reorder(celltype, -median_group), value, fill = variable)) +
    geom_bar(stat = "identity", position = "dodge") +
    coord_flip() +
    ylab("Overlap [%]") +
    xlab("") +
    theme_bw() +
    theme(text = element_text(size = 32)) +
    theme(legend.title = element_blank(), legend.position = c(0.85, 0.05))

  options(repr.plot.width = 12, repr.plot.height = 12)
  dodger <- position_dodge(width = 0.3)
  
  
  # Elements like pointrange and position_dodge only work when the outcome
  #   is mapped to y, need to go through with OR set as y then flip at the
  #   end
  op <- ggplot(sig_res, aes(y = odds, x = reorder(celltype, -median_group))) +
    geom_pointrange(aes(ymin = min, ymax = max),
      position = dodger,
      size = 1
    ) +
    geom_hline(yintercept = 1.0, linetype = "dotted", size = 1) +
    scale_y_log10(
      breaks = c(0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10),
      minor_breaks = NULL
    ) +
    labs(y = "Odds ratio") +
    coord_flip(ylim = c(0.1, 10)) +
    theme_bw() +
    theme(text = element_text(size = 32))

  n <- 13
  qual_col_pals <- brewer.pal.info[brewer.pal.info$category == "qual", ]
  col_vector <- unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

  p <- ggplot(
    data = sig_res,
    aes(x = reorder(celltype, -median_group), y = -log10(pvalue), fill = Cell_group)
  ) +
    geom_bar(stat = "identity") +
    theme_bw() +
    coord_flip() +
    labs(fill="Cell type")+
    theme(text = element_text(size = 32)) +
    scale_fill_manual(values = col_vector)

  
  options(repr.plot.width = w, repr.plot.height = h)

  cowplot::plot_grid(pper, op +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.y = element_blank()
    ), p +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.y = element_blank()
    ), nrow = 1, rel_widths = c(2, 0.4, 1))
}
```

## Plot results
```{r}
stemi_plot <- enrichment_cells("test/main.STEMI.csv", "STEMI_DR_full.csv", w = 36, h = 28)
nstemi_plot <- enrichment_cells("test/main.NSTEMI.csv", "NSTEMI_DR_full.csv", w = 36, h = 14)
ua_plot <- enrichment_cells("test/main.UA.csv", "UA_DR_full.csv", w = 36, h = 14)
```

```{r Make_Publication_Figure_S5}
options(repr.plot.width = 36, repr.plot.height = 48)
cowplot::plot_grid(stemi_plot, nstemi_plot +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank()
  ),
ua_plot,
nrow = 3, rel_heights = c(7, 1.5, 1.7),
labels = c("STEMI", "NSTEMI", "UA"), label_size = 32
)
```
