---
title: "Evaluate Cell-type signature matrix using deconvR"
output: html_notebook
---

# Goal 

In this notebook we want to evaluate the performance of our extended reference atlas/ CpG signature matrix compared to the comprehensive reference atlas generated by Moss et al (2018).


```{r}
# BiocManager::install("deconvR")
library("deconvR")
library(ggplot2)
library(dplyr)
# library(tidyverse)
```

```{r}
fullMethAtlas <- fread("/data/local/agosdsc/projects/AAkalin_cfdTissue/meth_atlas-master/full_atlas.csv.gz")
fullMethAtlasSampleNames <- fread("/data/local/agosdsc/projects/AAkalin_cfdTissue/meth_atlas-master/reference_atlas.csv",nrows = 1)
names(fullMethAtlas) <- names(fullMethAtlasSampleNames)
names(fullMethAtlas)[1] <- "IDs"
ReferencMethAtlas <- fread("/data/local/agosdsc/projects/AAkalin_cfdTissue/meth_atlas-master/reference_atlas.csv")
encodeHeartMeta <- fread("/data/local/agosdsc/projects/AAkalin_cfdTissue/encode_heartsamples/metadata.tsv")
names(encodeHeartMeta) <- gsub(" ","_",names(encodeHeartMeta))

encodeHeartSamples <- fread("/data/local/agosdsc/projects/AAkalin_cfdTissue/encode_heartsamples/encode_heartsamples.csv")
names(encodeHeartSamples)[1] <- "IDs"

extendedReference <- fread("/data/local/agosdsc/projects/AAkalin_cfdTissue/results/extendedReference.csv",data.table = FALSE)
names(extendedReference)[1] <- "IDs"

extendedMethAtlas <- fread("/data/local/agosdsc/projects/AAkalin_cfdTissue/preprocessed/filteredExtendedMethAtlas_pooledEncode.tsv",data.table = TRUE)
names(extendedMethAtlas)[1] <- "IDs"
```


```{r}
# data("HumanCellTypeMethAtlas")
# exampleSamples <- simulateCellMix(1,
#   reference = HumanCellTypeMethAtlas
# )$simulated
# exampleMeta <- data.table(
#   "Experiment_accession" = "example_sample",
#   "Biosample_term_name" = "example_cell_type"
# )
colnames(encodeHeartSamples)[1] <- c("CpGs")
colnames(fullMethAtlas)[1] <- c("CpGs")


# requires deconvr >= 1.4
# signatures <- findSignatures(
#   samples = encodeHeartSamples,
#   sampleMeta = encodeHeartMeta,
#   atlas = fullMethAtlas,
#   tissueSpecCpGs = FALSE
# )
```

## Evaluate on full meth atlas


```{r}
# n_tissues = 25
# ref <- extendedReference[,c(1, 18, 27,28,29)]
ref <- as.data.frame(fullMethAtlas)
cellTypes <- names(ref)[-1]
# mixingVector : Specify the cell origin proportions.If numberOfSamples = 1, this can be a vector of length = number of cell types in reference.Otherwise, this is a dataframe with rows for cell types (must be equal to cell types in reference) and columns for samples.
mixVec <- as.data.frame(diag(x = 1/length(cellTypes), nrow = length(cellTypes), ncol = length(cellTypes)) +
                        sample(x = seq(from = 0.01, to = 0.3,by = 0.01),size = ncol(ref)-1,replace = TRUE)
                        )

# mixVec <- rep(1/(ncol(ref)-1),ncol(ref)-1)
# # mixVec[c(17)] <- 1
# mixVec <- mixVec + sample(x = seq(from = 0.01, to = 0.1,by = 0.01),size = ncol(ref)-1,replace = TRUE)

nSamples <- length(cellTypes)
set.seed(123)
cellMix <- simulateCellMix(numberOfSamples = 100,
                           # mixingVector = mixVec,
                           reference = ref)
reshape::melt(cellMix$proportions) %>% 
    ggplot(data = ., aes(x = variable, y = value)) + 
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

cellMix$proportions %>% 
    pheatmap::pheatmap(cluster_rows = FALSE, cluster_cols = FALSE)
```

```{r}
set.seed(123)
cellMix_deconvMethAtlas <- suppressWarnings(deconvolute(reference = HumanCellTypeMethAtlas, 
                                       bulk = cellMix$simulated,# %>% filter(.$IDs %in% HumanCellTypeMethAtlas$IDs), 
                                       model = "nnls"))
reshape::melt(cellMix_deconvMethAtlas$proportions) %>% 
    ggplot(data = ., aes(x = variable, y = value)) + 
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

cellMix_deconvMethAtlas$proportions %>% 
    pheatmap::pheatmap(cluster_cols = FALSE, cluster_rows = FALSE)

RMSE(unlist(cellMix$proportions) , unlist(cellMix_deconvMethAtlas$proportions))
```
```{r}
cellMix_deconvextendedReference <- suppressWarnings(deconvolute(reference = extendedReference,
                                               bulk = cellMix$simulated,# %>% filter(.$IDs %in% extendedReference$IDs),
                                               model = "nnls"))
reshape::melt(cellMix_deconvextendedReference$proportions) %>% 
    ggplot(data = ., aes(x = variable, y = value)) + 
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

cellMix_deconvextendedReference$proportions %>% 
    pheatmap::pheatmap(cluster_cols = FALSE, cluster_rows = FALSE)

RMSE(obs = unlist(cellMix$proportions), pred = unlist(cellMix_deconvextendedReference$proportions[,-c(26:28)]))
```

## Evaluate on heart tissue samples

```{r}
set.seed(123)
encodeMixedHeartSamples <- cbind(encodeHeartSamples[,1],
                                 "Mix" = Reduce(f = `+`, 
                                                x = lapply(encodeHeartSamples[,-1], function(x) x))/(ncol(encodeHeartSamples)-1)
                                 )
```

```{r}
set.seed(123)
cellMix_deconvMethAtlas <- deconvolute(reference = HumanCellTypeMethAtlas, 
                                       bulk = encodeMixedHeartSamples,# %>% filter(.$IDs %in% HumanCellTypeMethAtlas$IDs), 
                                       model = "nnls")
reshape::melt(cellMix_deconvMethAtlas$proportions) %>% 
    ggplot(data = ., aes(x = variable, y = value)) + 
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

cellMix_deconvMethAtlas$proportions %>% 
    pheatmap::pheatmap(cluster_cols = FALSE, cluster_rows = FALSE)


RMSE(obs = unlist(cellMix$proportions) , pred = unlist(cellMix_deconvMethAtlas$proportions))
```


```{r}
cellMix_deconvextendedReference <- deconvolute(reference = extendedReference,
                                               bulk = encodeMixedHeartSamples,# %>% filter(.$IDs %in% extendedReference$IDs),
                                               model = "nnls")
reshape::melt(cellMix_deconvextendedReference$proportions) %>% 
    ggplot(data = ., aes(x = variable, y = value)) + 
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

cellMix_deconvextendedReference$proportions %>% 
    pheatmap::pheatmap(cluster_cols = FALSE, cluster_rows = FALSE)

RMSE(obs = unlist(cellMix$proportions), pred = unlist(cellMix_deconvextendedReference$proportions))
```

```{r}

gplots::venn(data = list(HumanCellTypeMethAtlas = HumanCellTypeMethAtlas$IDs, 
                         extendedReference = extendedReference$IDs))

```


