---
title: "RoadMap_enrichment"
output: html_notebook
---

# Load Libraries
```{r}
require(tidyverse)
library(reshape2)
library(GenomicRanges)
require(RColorBrewer)
```

# Load input data
```{r}
road_map <- read.table("/local/rcuadrat/cfDNAprioritize/databases/prom_enh.csv", sep = "\t", header = TRUE)
main <- read.table("/local/rcuadrat/cfDNAprioritize/test/main.STEMI.csv", header = TRUE)
samples <- read.table("/local/rcuadrat/cfDNAprioritize/test/samples.STEMI.csv", header = TRUE)

##edited from unfactor() to unlist()
cell_types <- (unlist(unique(road_map$Sample_desc)))

Heart_vascular <- c("Fetal Heart", "Right Atrium", "Left Ventricle", "Right Ventricle", "Aorta", "HUVEC Umbilical Vein Endothelial Primary Cells")

Carcinoma <- cell_types[grep("Carcinoma", cell_types)]
Blood <- cell_types[grep("blood|T helper|Leukemia|Monocytes", cell_types)]
Skeletal_Muscle <- cell_types[grep("Skeletal Muscle|Fetal Muscle|Psoas|Muscle Satellite", cell_types)]
Stem <- cell_types[grep("Stem|stem|ES|H1|H9|hESC|iPS|HUE", cell_types)]
Nervous_system <- cell_types[grep("Brain|neurospheres", cell_types)]
Digestive <- cell_types[grep("Stomach|Gastric|Esophagus|Intestine|Duodenum|Rectal|Colonic|Colon", cell_types)]
Foreskin <- cell_types[grep("Foreskin", cell_types)]
Lung <- cell_types[grep("Lung|lung", cell_types)]
Lung <- Lung[!grepl("Carcinoma", Lung)]
Breast <- cell_types[grep("Breast|HMEC", cell_types)]
Pancreas <- cell_types[grep("Pancrea", cell_types)]
Lymphatic <- cell_types[grep("Thymus|Spleen", cell_types)]
cells_tissues_groups <- cbind(
  Heart_vascular, Carcinoma, Blood, Skeletal_Muscle, Stem, Nervous_system, Digestive,
  Foreskin, Lung, Breast, Pancreas, Lymphatic
)
cells_tissues_groups <- melt(cells_tissues_groups) %>%
  dplyr::select(-Var1) %>%
  unique()
Others <- cell_types[!(cell_types %in% cells_tissues_groups$value)]
Others <- data.frame("Others", Others)
names(Others) <- c("Var2", "value")
cells_tissues_groups <- rbind(cells_tissues_groups, Others)
names(cells_tissues_groups) <- c("Cell_group", "celltype")
```

# Analysis
## Testing things here
```{r Testing_1}
percc <- t(main[1, ] %>% dplyr::select(-chr, -start, -end))
samples <- samples %>% column_to_rownames(var = "sampleId")
meeerge <- merge(samples, percc, by = 0)
```


```{r Testing_2}
p <- ggplot(meeerge, aes(x = Type, y = meeerge[, 3], fill = Type)) +
  geom_boxplot() +
  theme_bw()
p
```

## Annotate DMR roadmap
```{r Function_Annotate_DMR_roadmap}
annotate_DMR_roadmap <- function(DMRs, road_map) {
  # make a Genomic range with DMR tiles
  main <- DMRs
  nDMRs <- nrow(main)
  road_map <- road_map
  gr_DMR <- makeGRangesFromDataFrame(main %>% dplyr::select(chr, start, end))

  # find overlap with road_map enhancers/promoters on DMR tiles
  tmp_bed2 <- findOverlaps(gr_DMR, as(road_map, "GRanges"))
  tmp_bed2 <- data.frame(tmp_bed2)
  tmp_bed3 <- data.frame(gr_DMR[tmp_bed2$queryHits])
  tmp_bed4 <- data.frame(as(road_map, "GRanges")[tmp_bed2$subjectHits])
  tmp_bed4 <- tmp_bed4 %>% dplyr::select(SampleID, Sample_desc)
  final_enhancer_annotated <- merge(tmp_bed3, tmp_bed4, by = 0)
  final_enhancer_annotated$DMR <- paste0(final_enhancer_annotated$seqnames, "_", final_enhancer_annotated$start, "_", final_enhancer_annotated$end)
  final_enhancer_annotated <- final_enhancer_annotated %>% dplyr::select(DMR, Sample_desc)
  final_enhancer_annotated <- final_enhancer_annotated %>% unique()

  enh_matrix <- dcast(final_enhancer_annotated, DMR ~ Sample_desc, length)
  enh_matrix <- enh_matrix %>%
    remove_rownames() %>%
    column_to_rownames(var = "DMR")

  # count number of DMR tiles annotated for each celltype, calculate perc of those of the total tiles on DMR
  disease_enhancer_annotated <- data.frame(colSums(enh_matrix), (colSums(enh_matrix) / nDMRs * 100))
  names(disease_enhancer_annotated) <- c("DMR", "perc_DMR")
  out <- list(disease_enhancer_annotated, final_enhancer_annotated)
  names(out) <- c("disease_enhancer_annotated", "final_enhancer_annotated")
  return(out)
}
```

```{r Run_function_annotate_DMR_roadmap}
result <- annotate_DMR_roadmap(main, road_map)
```

```{r Collapse_result}
result$final_enhancer_annotated %>%
  separate(DMR, c("chr", "start", "end")) %>%
  group_by(chr, start, end) %>%
  mutate(Sample_desc = paste0(Sample_desc, collapse = "|")) %>%
  unique()
```

## Extract a background and run enrichment test for cell types on DMRs
```{r Function_background_and_enrichment_tests}
enrichment_cells <- function(DMRs, DM) {
  main <- read.table(DMRs, header = TRUE)
  # get just regions of DMR
  DMRs <- main %>% dplyr::select(chr, start, end)
  # calculate 1000bp distant tiles
  DMRs$start_prev <- DMRs$start - 1000
  DMRs$end_prev <- DMRs$end - 1000

  DMRs$start_after <- DMRs$start + 1000
  DMRs$end_after <- DMRs$end + 1000

  # getting the regions after and before DMR (1000bp distant)
  prev <- DMRs %>%
    dplyr::select(chr, start_prev, end_prev) %>%
    dplyr::rename("start" = "start_prev", "end" = "end_prev")
  after <- DMRs %>%
    dplyr::select(chr, start_after, end_after) %>%
    dplyr::rename("start" = "start_after", "end" = "end_after")
  background_regions <- rbind(prev, after)

  DM_test <- read.table(DM, sep = "\t", header = TRUE)
  DM_test <- DM_test %>% dplyr::rename("chr" = "seqnames")
  background_regions <- merge(background_regions, DM_test, by = c("chr", "start", "end"), all.x = TRUE)
  background_regions_notsig <- background_regions %>% dplyr::filter(qvalue > 0.05 | is.na(qvalue))
  background <- background_regions_notsig %>% dplyr::select(chr, start, end)
  # number of tiles in the background
  ntiles <- nrow(background)
  # make a Genomic range with background tiles
  gr_background <- makeGRangesFromDataFrame(background)

  # find overlap with road_map enhancers/promoters on background tiles
  tmp_bed2 <- findOverlaps(gr_background, as(road_map, "GRanges"))
  tmp_bed2 <- data.frame(tmp_bed2)
  tmp_bed3 <- data.frame(gr_background[tmp_bed2$queryHits])
  tmp_bed4 <- data.frame(as(road_map, "GRanges")[tmp_bed2$subjectHits])
  tmp_bed4 <- tmp_bed4 %>% dplyr::select(SampleID, Sample_desc)
  background_enhancer_annotated <- merge(tmp_bed3, tmp_bed4, by = 0)
  background_enhancer_annotated$DMR <- paste0(background_enhancer_annotated$seqnames, "_", background_enhancer_annotated$start, "_", background_enhancer_annotated$end)
  background_enhancer_annotated <- background_enhancer_annotated %>% dplyr::select(DMR, Sample_desc)
  background_enhancer_annotated <- background_enhancer_annotated %>% unique()

  background_enhancer_matrix <- dcast(background_enhancer_annotated, DMR ~ Sample_desc, length)
  background_enhancer_matrix <- background_enhancer_matrix %>%
    remove_rownames() %>%
    column_to_rownames(var = "DMR")

  # count number of background tiles annotated for each celltype, calculate perc of those of the total tiles on background
  background_enhancer_annotated <- data.frame(colSums(background_enhancer_matrix), (colSums(background_enhancer_matrix) / ntiles * 100))
  names(background_enhancer_annotated) <- c("Background", "perc_Background")

  # processing main file with DMRs
  # making a genomic range out of it, looking for overlaps with df3 that is
  # the roadmap dataframe with promoters and enhanceers regions for cell types
  # main=read.table("test/main.STEMI.csv",header=TRUE)
  # number of tiles in the DMR results
  nDMRs <- nrow(main)
  # make a Genomic range with DMR tiles
  gr_DMR <- makeGRangesFromDataFrame(main %>% dplyr::select(chr, start, end))
  # find overlap with road_map enhancers/promoters on DMR tiles
  tmp_bed2 <- findOverlaps(gr_DMR, as(road_map, "GRanges"))
  tmp_bed2 <- data.frame(tmp_bed2)
  tmp_bed3 <- data.frame(gr_DMR[tmp_bed2$queryHits])
  tmp_bed4 <- data.frame(as(road_map, "GRanges")[tmp_bed2$subjectHits])
  tmp_bed4 <- tmp_bed4 %>% dplyr::select(SampleID, Sample_desc)
  final_enhancer_annotated <- merge(tmp_bed3, tmp_bed4, by = 0)
  final_enhancer_annotated$DMR <- paste0(final_enhancer_annotated$seqnames, "_", final_enhancer_annotated$start, "_", final_enhancer_annotated$end)
  final_enhancer_annotated <- final_enhancer_annotated %>% dplyr::select(DMR, Sample_desc)
  final_enhancer_annotated <- final_enhancer_annotated %>% unique()

  enh_matrix <- dcast(final_enhancer_annotated, DMR ~ Sample_desc, length)
  enh_matrix <- enh_matrix %>%
    remove_rownames() %>%
    column_to_rownames(var = "DMR")

  # count number of DMR tiles annotated for each celltype, calculate perc of those of the total tiles on DMR
  disease_enhancer_annotated <- data.frame(colSums(enh_matrix), (colSums(enh_matrix) / nDMRs * 100))
  names(disease_enhancer_annotated) <- c("DMR", "perc_DMR")

  # merge background and disease counts and percs
  final_perc <- merge(background_enhancer_annotated, disease_enhancer_annotated, by = 0)
  final_perc <- final_perc %>%
    # remove_rownames() %>%
    column_to_rownames(var = "Row.names")

  nDMRs <- nrow(main)
  ntiles <- nrow(background_regions_notsig)

  results <- data.frame(matrix(ncol = 5))
  x <- c("celltype", "pvalue", "odds", "min", "max")
  colnames(results) <- x
  for (row in 1:nrow(final_perc)) {
    not_cell_back <- ntiles - final_perc$Background[row]

    not_cell_DMR <- nDMRs - final_perc$DMR[row]

    tab_cont <- matrix(c(final_perc$Background[row], not_cell_back, final_perc$DMR[row], not_cell_DMR), nrow = 2, ncol = 2)

    fisher_result <- fisher.test(tab_cont)
    pvalue <- fisher_result$p.value
    min <- fisher_result$conf.int[1]
    max <- fisher_result$conf.int[2]
    odds <- fisher_result$estimate[[1]]
    celltype <- row.names(final_perc[row, ])
    a <- data.frame(celltype = celltype, pvalue = pvalue, odds = odds, min = min, max = max)
    results <- rbind(results, a)
  }
  results <- results[-1, ]

  sig_res <- results %>% dplyr::filter(pvalue <= 0.05 / 127)


  melt_perc <- melt(final_perc %>% rownames_to_column("celltype") %>% dplyr::select(celltype, perc_Background, perc_DMR))
  sig_res <- merge(sig_res, melt_perc, by = "celltype")
  sig_res$variable <- gsub("perc_", "", sig_res$variable)
  sig_res <- merge(sig_res, cells_tissues_groups, by = "celltype")


  sig_res$celltype <- as.factor(sig_res$celltype)
  sig_res <- sig_res %>%
    group_by(Cell_group) %>%
    mutate(median_group = median(pvalue))
  sig_res <- ungroup(sig_res)

  levels(sig_res$Cell_group) <- c("Heart vascular",  "Carcinoma", "Blood", "Skeletal muscle", "Stem", "Nervous system",  "Digestive", "Foreskin", "Lung", "Breast", "Pancreas", "Lymphatic", "Others")
  
  levels(sig_res$celltype) <- c(
  "A549 EtOH 0.02pct Lung Carcinoma Cell Line", "Adipose Derived Mesenchymal Stem Cell Cultured Cells", "Adipose Nuclei",
  "     Bone Marrow Derived Cultured Mesenchymal Stem Cells", "Brain Angular Gyrus", "Brain Anterior Caudate",
  "Brain Cingulate Gyrus", "Brain Germinal Matrix", "Brain Hippocampus Middle",
  "Brain Inferior Temporal Lobe", "Brain Substantia Nigra", "Brain Dorsolateral Prefrontal Cortex",
  "Breast Myoepithelial Primary Cells", "Breast variant Human Mammary Epithelial Cells (vHMEC)", "Colon Smooth Muscle",
  "Dnd41 TCell Leukemia Cell Line", "Duodenum Mucosa", "Duodenum Smooth Muscle",
  "Fetal Adrenal Gland", "Fetal Intestine Small", "Fetal Kidney",
  "Fetal Lung", "Fetal Stomach", "Fetal Thymus",
  "Foreskin Fibroblast Primary Cells skin01", "Foreskin Fibroblast Primary Cells skin02", "Foreskin Keratinocyte Primary Cells skin02",
  "Foreskin Keratinocyte Primary Cells skin03", "Foreskin Melanocyte Primary Cells skin01", "GM12878 Lymphoblastoid Cells",
  "Ganglion Eminence derived primary cultured neurospheres", "HMEC Mammary Epithelial Primary Cells", "HSMM Skeletal Muscle Myoblasts Cells",
  "HUVEC Umbilical Vein Endothelial Primary Cells", "HeLa-S3 Cervical Carcinoma Cell Line", "IMR90 fetal lung fibroblasts Cell Line",
  "K562 Leukemia Cells", "Liver", "Mesenchymal Stem Cell Derived Adipocyte Cultured Cells",
  "Mesenchymal Stem Cell Derived Chondrocyte Cultured Cells", "Monocytes-CD14+ RO01746 Primary Cells", "Muscle Satellite Cultured Cells",
  "NHEK-Epidermal Keratinocyte Primary Cells", "Osteoblast Primary Cells", "Primary B cells from cord blood",
  "Primary B cells from peripheral blood", "Primary Natural Killer cells from\302\240peripheral\302\240blood", "Primary T CD8+ naive cells from peripheral blood",
  "Primary T cells from\302\240peripheral\302\240blood", "Primary T helper 17 cells PMA-I stimulated", "Primary T helper cells PMA-I stimulated",
  "Primary T helper naive cells from peripheral blood", "Primary T regulatory cells from\302\240peripheral\302\240blood", "Primary hematopoietic stem cells G-CSF-mobilized Female",
  "Primary hematopoietic stem cells G-CSF-mobilized Male", "Primary hematopoietic stem cells short term culture", "Primary monocytes from\302\240peripheral\302\240blood",
  "Primary neutrophils from\302\240peripheral\302\240blood", "Rectal Mucosa Donor 31", "Rectal Smooth Muscle",
  "Skeletal Muscle Female", "Skeletal Muscle Male", "Stomach Mucosa",
  "Stomach Smooth Muscle", "hESC Derived CD184+ Endoderm Cultured Cells")
  
  return(sig_res)
}
```

## Plot results
```{r Run_function}
stemi_enrichment <- enrichment_cells("/local/rcuadrat/cfDNAprioritize/test/main.STEMI.csv", "/local/AAkalin_cardiac/Results/cardiac/from-rafael/STEMI_DR_full.csv") #, w = 36, h = 28)
nstemi_enrichment <- enrichment_cells("/local/rcuadrat/cfDNAprioritize/test/main.NSTEMI.csv", "/local/AAkalin_cardiac/Results/cardiac/from-rafael/NSTEMI_DR_full.csv") #, w = 36, h = 14)
ua_enrichment <- enrichment_cells("/local/rcuadrat/cfDNAprioritize/test/main.UA.csv", "/local/AAkalin_cardiac/Results/cardiac/from-rafael/UA_DR_full.csv") #, w = 36, h = 14)
```
```{r Stemi_plotting}
color_selection <- RColorBrewer::brewer.pal(n=8, name="Dark2")[c(8,6)]
  
  left_stemi <- ggplot(stemi_enrichment, aes(reorder(celltype, -median_group), value, fill = variable)) +
    geom_bar(stat = "identity", position = "dodge") +
    coord_flip() +
    ylab("Overlap [%]") +
    xlab("") +
    theme_bw() +
    labs(fill="Region")+
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        axis.title.x = element_blank())+
    scale_fill_manual(values=color_selection)
  
  #options(repr.plot.width = 12, repr.plot.height = 12)
  #dodger <- position_dodge(width = 0.3)
  
  # Elements like pointrange and position_dodge only work when the outcome
  #   is mapped to y, need to go through with OR set as y then flip at the
  #   end
  middle <- ggplot(stemi_enrichment, aes(y = odds, x = reorder(celltype, -median_group))) +
    geom_pointrange(aes(ymin = min, ymax = max),
      position = dodger,
      size = 1
    ) +
    geom_hline(yintercept = 1.0, linetype = "dotted", size = 1) +
    scale_y_log10(
      breaks = c(0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10),
      minor_breaks = NULL
    ) +
    labs(y = "Odds ratio") +
    coord_flip(ylim = c(0.2, 1.6)) +
    theme_bw() +
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        axis.title = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        )          

  right_stemi <- ggplot(
    data = stemi_enrichment,
    aes(x = reorder(celltype, -median_group), y = -log10(pvalue), fill = Cell_group)
  ) +
    geom_bar(stat = "identity") +
    theme_bw() +
    coord_flip() +
    labs(fill="Cell type")+
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        axis.title = element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank())          +
    scale_fill_brewer(palette="Paired")
  

#Unite all figures in panel  
  stemi_panel<-cowplot::plot_grid(left_stemi+theme(legend.position = "none"), middle, right_stemi+theme(legend.position = "none"), nrow = 1, rel_widths = c(2, 0.4, 1))
```

```{r Nstemi_plotting}
  left <- ggplot(nstemi_enrichment, aes(reorder(celltype, -median_group), value, fill = variable)) +
    geom_bar(stat = "identity", position = "dodge") +
    coord_flip() +
    ylab("Overlap [%]") +
    xlab("") +
    theme_bw() +
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        legend.title = element_blank(), 
        legend.position = "none",
        axis.title.x = element_blank())+
    scale_fill_manual(values=color_selection)
  
  #options(repr.plot.width = 12, repr.plot.height = 12)
  #dodger <- position_dodge(width = 0.3)
  
  # Elements like pointrange and position_dodge only work when the outcome
  #   is mapped to y, need to go through with OR set as y then flip at the
  #   end
  middle <- ggplot(nstemi_enrichment, aes(y = odds, x = reorder(celltype, -median_group))) +
    geom_pointrange(aes(ymin = min, ymax = max),
      position = dodger,
      size = 1
    ) +
    geom_hline(yintercept = 1.0, linetype = "dotted", size = 1) +
    scale_y_log10(
      breaks = c(0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10),
      minor_breaks = NULL
    ) +
    labs(y = "Odds ratio") +
    coord_flip(ylim = c(0.2, 1.6)) +
    theme_bw() +
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        axis.title = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        )          

  right <- ggplot(
    data = nstemi_enrichment,
    aes(x = reorder(celltype, -median_group), y = -log10(pvalue), fill = Cell_group)
  ) +
    geom_bar(stat = "identity") +
    theme_bw() +
    coord_flip() +
    labs(fill="Cell type")+
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        axis.title = element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        legend.position = "none")          +
    scale_fill_brewer(palette="Paired")
  

#Unite all figures in panel  
nstemi_panel<-cowplot::plot_grid(left, middle, right, nrow = 1, rel_widths = c(2, 0.4, 1))
```

```{r UA_plotting}
  left <- ggplot(ua_enrichment, aes(reorder(celltype, -median_group), value, fill = variable)) +
    geom_bar(stat = "identity", position = "dodge") +
    coord_flip() +
    ylab("Overlap [%]") +
    xlab("") +
    theme_bw() +
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        legend.title = element_blank(), 
        legend.position = "none")+
    scale_fill_manual(values=color_selection)
  
  #options(repr.plot.width = 12, repr.plot.height = 12)
  #dodger <- position_dodge(width = 0.3)
  
  # Elements like pointrange and position_dodge only work when the outcome
  #   is mapped to y, need to go through with OR set as y then flip at the
  #   end
  middle <- ggplot(ua_enrichment, aes(y = odds, x = reorder(celltype, -median_group))) +
    geom_pointrange(aes(ymin = min, ymax = max),
      position = dodger,
      size = 1
    ) +
    geom_hline(yintercept = 1.0, linetype = "dotted", size = 1) +
    scale_y_log10(
      breaks = c(0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10),
      minor_breaks = NULL
    ) +
    labs(y = "Odds ratio") +
    coord_flip(ylim = c(0.2, 1.6)) +
    theme_bw() +
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        axis.title.y = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        )          

  right <- ggplot(
    data = ua_enrichment,
    aes(x = reorder(celltype, -median_group), y = -log10(pvalue), fill = Cell_group)
  ) +
    geom_bar(stat = "identity") +
    theme_bw() +
    coord_flip() +
    labs(fill="Cell type")+
    theme(text = element_text(size = 32),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(colour = NA),        
        axis.line.x = element_line(colour = "black"),
        axis.line.y = element_line(colour = "black"),
        axis.title.y = element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        legend.position = "none")          +
    scale_fill_brewer(palette="Paired")
  

#Unite all figures in panel  
ua_panel<-cowplot::plot_grid(left, middle, right, nrow = 1, rel_widths = c(2, 0.4, 1))
```
```{r, fig.width=20, fig.height=30}
stemi_panel
```

```{r Make_Publication_Figure_S5, fig.width=36, fig.height=48}
legend_1 <- cowplot::get_legend(right_stemi + theme(legend.box.margin = margin(0, 0, 0, 12)))
legend_2 <- cowplot::get_legend(left_stemi + theme(legend.box.margin = margin(0,0,0,12)))


options(repr.plot.width = 36, repr.plot.height = 48)

all_panels <- cowplot::plot_grid(stemi_panel, nstemi_panel, ua_panel,
nrow = 3, ncol=1, rel_heights = c(nrow(stemi_enrichment)-25, nrow(nstemi_enrichment), nrow(ua_enrichment)),
labels = c("STEMI", "NSTEMI", "UA"), 
label_size = 50,
label_x = -0.0001,
label_y = 1,
align="hv",
hjust=0)
 
legends <- cowplot::plot_grid(legend_1, legend_2, nrow=9, align = "v")
cowplot::plot_grid(all_panels, legends, ncol=2, rel_widths = c(0.8, 0.2))
ggsave(filename="/local/AAkalin_cardiac/Results/cardiac/Plots/FigureS5.pdf", units = "in", width=36, height=48, bg="white")

```







